name = "Porosity"
uuid = "35db7a65-4993-4cb4-8bbd-c48e232b3666"
authors = ["Abhinav Pratap Singh <abhinavps0905@gmail.com>"]
version = "0.1.4"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NonlinearSolve = "8913a72c-1f9b-4ce2-8d82-65094dcecaec"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
SubsurfaceCore = "3a78539b-9dce-42c5-be8d-f3fa4153f7a3"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"

[compat]
Distributions = "0.25.122"
NonlinearSolve = "4.12.0"
QuadGK = "2.11.2"
Reexport = "1.2.2"
SpecialFunctions = "2.5.1"
Statistics = "1.11.1"
SubsurfaceCore = "0.7"
UnPack = "1.0.2"
julia = "1.11"

[extras]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Hwloc = "0e44f5e4-bd66-52a0-8798-143a42290a1d"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
ReTestItems = "817f1d60-ba6b-4fd5-9520-3cf149f6a823"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["BenchmarkTools", "Test", "ReTestItems", "JET", "Hwloc", "InteractiveUtils"]
