name: "Tests"

on:
  push:
    paths-ignore:
      - 'docs/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref_name != github.event.repository.default_branch || github.ref != 'refs/tags/v*' }}

jobs:
  tests:
    runs-on: 'ubuntu-latest'
    name: "Tests"
    strategy:
      fail-fast: false
      matrix:
        version: ["1.11"]
        group:
          - "cond"
          - "elastic"
          - "visc"
          - "anelastic"
          - "phase_mixing"
          - "combine_models"
    steps:
      - uses: actions/checkout@v4

      - name: "Setup Julia ${{ matrix.version }}"
        uses: julia-actions/setup-julia@v2
        with:
          version: "${{ matrix.version }}"

      - name: "Run tests with Julia v${{ matrix.version }}"
        uses: julia-actions/julia-runtest@v1
        env:
          GROUP: "${{ matrix.group }}"

      - uses: julia-actions/julia-processcoverage@v1
        with:
          directories: "src"
